# Generated by Django 5.2.5 on 2025-09-01 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='mibase.universidad')),
            ],
        ),
    ]
