# Generated by Django 5.2.5 on 2025-09-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('gmail', models.EmailField(max_length=254)),
                ('interes', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
